name: Actualizar docker en DockerHub
on: 
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
    branches:
      - main
jobs:
  actualizar_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba repo
        uses: actions/checkout@v2
      - name: Build y push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }} 
          tags: latest
