name: Actualizar docker en DockerHub
on: 
  push:
jobs:
  actualizar_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba repo
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          repository: eantoniocalo18/iv
          tags: latest 
          
